views/includes/block-content.pug
bitcoin-abc is a fork from bitcoin-core. Now bitcoin-abc has remove weight item from the rpc command(bitcoin-cli getblock blockhash). This modification will be friendly to support bitcoin-abc(BCH).
The difference is:
```
bitcoin/src$ bitcoin-cli getblock 00000000000000000019afc3cf0f12414c3b03cc36b10964922d86d7c7cd8498
{
"hash": "00000000000000000019afc3cf0f12414c3b03cc36b10964922d86d7c7cd8498",
"confirmations": 1,
"strippedsize": 50447,
"size": 66460,
"weight": 217801,
"height": 515053,
"version": 536870912,
"versionHex": "20000000",
"merkleroot": "87d24c7880ce75eea74be50b0fbccbeb3d25eeb0d7b84996a412168c2b2a894e",
"tx": [
"34a42eb61a7f0685de8db7784a541bf4d5a88fa60d5edcba0112b10ca4b0cc6f",
"94741527a643eab80266e52a745e53217596c36184240c41a0f374f8850c34e9", …
```
=> fix block weight item for supporting bitcoin-abc

routes/baseActionsRouter.js
Fixes sendtoaddress RCP call. Currently specifying amount argument gets lost from request: 
```
Executing RPC 'sendtoaddress' with params: [sgbfXLGi3VJnvKKu7ZMpMCZQvEiPRTSDox,]
RPC Response: err=null, result=RpcError: -3 Amount is not a number or string, headers=undefined
```
=> Argument type fix

app/config.js
Without this fix, running btc-rpc-explorer without setting `BTCEXP_ELECTRUMX_SERVERS` was being parsed as single empty-string server, which resulted in the following error:
```
btc-rpc-explorer/app/config.js:33
electrumXServers.push({protocol:uri.protocol.substring(0, uri.protocol.length - 1), host:uri.hostname, port:parseInt(uri.port)});
^
TypeError: Cannot read property 'substring' of null
at Object.<anonymous> (btc-rpc-explorer/app/config.js:33:47)
```
=> bugfix: Filter empty Electrum servers

app.js, views/layout.pug
It might not be when installing btc-rpc-explorer globally (via `npm install -g`).
Without this, running btc-rpc-explorer without `.git` resulted in:
```
fatal: Not a git repository (or any parent up to mount point /home/user)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Unhandled Rejection at: Promise Promise {
<rejected> TypeError: Cannot read property 'all' of null
at btc-rpc-explorer/app.js:334:35
```
=> Get sourcecodeVersion and sourcecodeDate only when .git is available

.env-sample
Sample .env file is confusing cos docker-compose doesn't catch spaces in environment variable declarations
=> Fix incorrect spaces in .env sample

routes/baseActionsRouter.js
Related to #84. These out-of-bound errors might happen not just in regtest, but also if we have a node that still hasn't synced at least one year of history, or with a node for an altcoin that's still less than 1 years old.
With this patch, btc-rpc-explorer will only display stats going back as far as it has available data for.
=> Limit stats intervals to the history we have available

Dockerfile
The building will happen on the regular `node:8` image, but the final image will run `node:8-alpine` which will reduce the image size from 960 MB to 120 MB
https://docs.docker.com/develop/develop-images/multistage-build/
=> Use Docker multistage build to reduce image size

npm-shrinkwrap.json
Found 5 low severity node vulnerability while installing. Running `npm audit fix` bumps the version of *lodash* from 4.17.15 to 4.17.19 which resolves 4 out of 5 vulnerability.
Perhaps using [snyk.io](https://snyk.io/) bot would fix such issues in the future.
=> fix 4 low severity node vulnerability

app/coins/btc.js
Either "Bill Gates'" or "Bill Gates's" would be correct here, the current way would mean his name is "Bill Gate"
=> Fix Bill Gates' name

README.md
By default `btc-rpc-explorer` listens on 127.0.0.1, so if you run `docker run -p 3002:3002 -it btc-rpc-explorer` it'll only accept connections from inside the container, and not on the host.
Passing in `-e BTCEXP_HOST=0.0.0.0` like:
```
docker run -it -p 3002:3002 -e BTCEXP_HOST=0.0.0.0 btc-rpc-explorer
```
Tells `btc-rpc-explorer` to accept connections from anywhere, which is safe because you can handle what the host port is listening on in Docker.
For example if you want to limit to only local connections with Docker you would do:
```
docker run -it -p 127.0.0.1:3002:3002 -e BTCEXP_HOST=0.0.0.0 btc-rpc-explorer
```
=> Fix Docker example in README.md

bin/www
By passing the value of the `BTCEXP_OLD_SPACE_MAX_SIZE` environment variable directly in to `v8.setFlagsFromString()` without sanitization it means that if untrusted code can set environment variables it could influence V8 behaviour.
As an example if some untrusted code was able to set:
```bash
BTCEXP_OLD_SPACE_MAX_SIZE="1024 --random-seed 1"
```
then `--max_old_space_size=1024 --random-seed 1` will get passed directly to V8 and set the seed for the Node.js random number generator to 1 rendering most cryptographic operations insecure.
This is low severity because it's unlikely untrusted code could set environment variables, but still worth sanitizing to be safe.
=> Sanitize V8 flag input

app/utils.js
This fixes an error when the block reward goes to zero.
With this bug it was not possible to load the website anymore, when the block reward went to zero.
=> Fix error when Block block rewards gets zero in Regtest

app/sso.js
As @shesek
[pointed out](https://github.com/janoside/btc-rpc-explorer/pull/260#discussion_r543884234)
the `replace` method would only replace the first occurrence, not all of
them. This change fixes it.
=> Fixed replacing when generating the SSO token

Dockerfile
apparently bootstrap_node.js wants to spawn git.
=> add git to a docker image, fixes #169

app.js
Without this, 404 pages hang forever without a reply.
=> Prevent 404 pages from hanging

.env-sample, app.js, app/api/coreApi.js, app/api/electrumAddressApi.js, app/api/rpcApi.js, app/config.js, app/utils.js, routes/apiRouter.js, routes/baseRouter.js, views/block-analysis.pug, views/includes/block-content.pug, views/includes/blocks-list.pug, views/includes/transaction-io-details.pug, views/layout.pug, views/mining-summary.pug, views/transaction.pug
This is an attempt to enable as much of the functionality as possible for pruned nodes and for nodes without `txindex`.
`txindex` related changes:
- Fetch block transactions with `getrawtransaction <txid> <blockhash>`. This works without `txindex`.
- Tolerate missing previous output information and render transactions without it.
- Support `/tx/<txid>?height=<height>` and link to it from block pages.
Pruning related changes:
- Fallback to `getblockheader` instead of `getblock` for pruned blocks. The txid list and weight/size information will be missing.
- Tolerate missing block stats.
- Extract the Bitcoin whitepaper from the UTXO set.
Tested functionality:
- **Homepage:** Fully functional (recent blocks are unpruned, extracting the coinbase tx no longer depends on txindex)
- **Blocks …
=> Graceful degradation for pruned and txindex-less nodes 

app/systemMonitor.js, package.json
`event-loop-stats` is currently the only dependency that fails the installation if the native module cannot be built. The other native modules (tiny-secp256k1 and dtrace) make some noise when they fail, but let the installation continue and everything appears to work afterwards.
With this PR, it will be possible to install btc-rpc-explorer without an environment for building native modules (i.e. no need for `build-essential` and `python3`). This was possible before event-loop-stats was introduced.
=> Make event-loop-stats optional

app/api/rpcApi.js, views/mempool-summary.pug
This is a minimum viable product feature for https://github.com/janoside/btc-rpc-explorer/issues/273
Based on the v3 branch. 
Nothing graphically fancy but you now can see how many blocks you need to wait for your transaction to confirm.
=> MVP locate tx in mempool

views/node-details.pug
I made this for myself so I share it.
- Support both BIP8 and BIP9 activation
- Support LOT=true and LOT=false
- Show last update of activation status
It would be really cool to show statistic of running signaling when the period will start but I don't know how to do that nicely.
It should be compatible with both Bitcoin clients (it works with BIP8)
=> Show BIP8/9 activation status of Taproot softfork in node details

app/api/rpcApi.js, app/utils.js, docs/api.md, routes/apiRouter.js
I'd like to expose more data as a restful api as requested in issue https://github.com/janoside/btc-rpc-explorer/issues/55
Is this in scope?
I want to check if ApiRouter.js is the appropriate place for these new routes? 
Is there some naming conventions or json object structures I should copy? (Maybe https://mempool.space/api)
For some basic ticker data I have used 
https://blockchain.info/q/getblockcount
https://blockchain.info/q/unconfirmedcount
https://blockchain.info/q/hashrate
https://blockchain.info/q/totalbc
https://mempool.space/api/v1/fees/recommended
Those would represent an MVP for my uses to be able to query my own node instead of those third parties.
As a second phase I would want to support looking up information by address (balance, received tx, sent tx) and txid as I …
=> API routes for ticker data use case

app/utils.js
=> app/utils.js: minerInfo only on mainnet

views/includes/index-network-summary.pug
This change disables Next Block inside Network Summary section for `signet`.
Compare https://signet.bitcoinexplorer.org/ with always-rotating progress indicator with https://ex.signet.bublina.eu.org/
=> index-network-summary: Next Block not on signet

routes/apiRouter.js
This pull requests adds the address, value and type information to vin for a transaction api results. This way the caller does not have to make multiple calls to get the vin information to get addresses and calculate the fee. I have calculated the fee and added it to the results as well.
This scenario came up when attempting to consume the tx API in my bitcoin-reports.com project.
=> tx api: add address, type, value to vin. add fee.

app/api/xyzpubAddressApi.js, routes/apiRouter.js
This new xyzpub API endpoint will return a list of txids associated with the xyzpub. 
If limit parameter is not set then it will grab all txids associated with the xyzpub. 
If limit is set it will grab only txids associated with the limit amount of receive and change addresses. Eg. limit is 1 means 1 receive and 1 change address, the first one in the bip32 path.
My plan is to use this endpoint with my bitcoin-reports.com site. I'm returning only unique txids to make the size of the result as small as possible. As well I do not want to fetch more than txids as it will slow down the endpoint.
=> new xyzpub API returns txids

CHANGELOG-API.md, docs/api.js, routes/apiRouter.js
With the recent market volatility I found it interesting to watch this metric, 24 hour volume in BTC, which is already available on the homepage of Bitcoin Explorer.
I have a ticker at home and want to display this metric using an API hence this pull request.
=> Feature api 24 hour volume in BTC

app/config.js
Remove duplicated word in description of `Next Block` site tool
Fixes #467
=> fix: stutter typo "for the the next block"

app/api/coreApi.js, docs/api.js, routes/apiRouter.js
As a consumer of the API I ran into the need for just the block header and not the whole block. 
Use case 1: showing a list of recent blocks on my site (and keep an archive).
Use case 2: call for the block header on the fly after consuming api/tx which returns block hash but not block height.
=> add block header API

routes/apiRouter.js
When using the tx API to get unconfirmed transaction data it is noted that the "time" field is not present. This new feature will allow the API consumer to display the mempool entry time in place of the time field that appears only after confirmation.
=> tx api: add mempool data for unconfirmed tx

docs/api.js, routes/apiRouter.js
Implementation of this feature request https://github.com/janoside/btc-rpc-explorer/issues/488
The Bitcoin Core getmempoolinfo is directly exposed via /mempool/info
=> expose mempool size and total fees in api

views/node-details.pug
- Corrected empty "HOST" field
- Added a link from "PEERS" field to Peers page
- Redefined forksUrls as a multiline variable (more readable)
- Added tooltips
=> Node details page improvements

views/includes/index-network-summary.pug
Addition of mempool total fees in the main page. This information complement the total number of transactions, for example it can indicate that many pending transactions are less worrying when the total fees are low.
It is already available without any further API request (in mempoolInfo variable).
The layout is *number of txns* / *blocks to clear* / *total fees* to make it similar to other fields in the page.
A tooltip has been defined on each of these 3 pieces of information with highlight colors describing the low/high/very high danger levels.
=> MEMPOOL field improvement in main page

views/peers.pug
This pr adds the [BIP-324](https://github.com/bitcoin/bips/blob/master/bip-0324.mediawiki) service name to the abbreviations, so it shows up in the list.
=> add P2P_V2 flag to servicename abbreviations

routes/apiRouter.js
We are in a high fee environment lately and I think it's useful to know the fees projected for the next block. Currently, the API is returning the fees from Core which has a long look-back and doesn't return a live value from the mempool.
=> API: add nextBlock fees min, median, max

views/includes/shared-mixins.pug
the check for unconfirmed transactions only checks if the `txBlockHeight` variable exists; since unconfirmed txns have a height of `-1`, it "exists", and the check passes. this pr checks `txBlockHeight > -1`.  
...dunno why the images wont load...
=> fix confirmed block count for unconfirmed txns

app/utils.js, npm-shrinkwrap.json
This corrects extended public decoding which crashed with error: TypeError: bs58check.decode is not a function.
Regression can be tested with xpub6CpihtY9HVc1jNJWCiXnRbpXm5BgVNKqZMsM4XqpDcQigJr6AHNwaForLZ3kkisDcRoaXSUms6DJNhxFtQGeZfWAQWCZQe1esNetx5Wqe4M on public demo.
Additionally set version 1.7.4 for axios to correct vulnerability detected by npm audit
=> Adapted to bs58check V4 new interface

npm-shrinkwrap.json
Version in npm-shrinkwrap.json was different from package.json. The consequence is that `npm install` command modified this file, which is not expected by people installing from source.
=> Axios version consistency

views/layout.pug
This simple input change avoids the query from being saved by the browser
=> Update layout.pug for privacy concerns

Dockerfile
Updates node.js to the current active LTS version. Version 16 seems unmaintained at this time. See
https://nodejs.org/en/about/previous-releases
I tested this on my own server and I didn't notice any difference between running on node.js 16 and 20.
=> Dockerfile: update node.js to 20

docker-compose.yml
It's ignored by compose anyway. See
https://docs.docker.com/reference/compose-file/version-and-name/
=> docker-compose.yml: remove obsolete version
