views/node-status.pug
=> Fix node-status page

bin/cli.js
Update CLI utility with `BASIC_AUTH_PASSWORD` & `ELECTRUMX_SERVERS`, alias `--coin` as `-C`
=> Update CLI utility

.gitignore, public/css/radial-progress.css
This makes the package `npm install`able directly from github.
Refs #93.
=> Check public/css/radial-progress.css into git

README.md
Note that the instructions here assumes #98 is merged. If #98 is not accepted, I'll update this PR accordingly.
=> Update README with easier installation instructions and new CLI utility

app.js, bin/refresh-mining-pool-configs.js
This wasn't detected correctly if the btc-rpc-explorer executable was started outside the source code directory.
See: https://github.com/janoside/btc-rpc-explorer/commit/69ab7548da805336079dc1ff6c62fb328ed0f879#r32280032
=> Fix mining pool config path

app/coins/btc.js
See https://bitcointalk.org/index.php?topic=293382.0
=> Update Fun with bounty P2SH addresses from 2013

app/coins/btc.js, app/utils.js
This PR adds the Bitcoin `signet` network and the new `v1_p2tr` output type.
=> Add signet and taproot support

app.js, app/utils.js, npm-shrinkwrap.json, package.json, routes/apiRouter.js, routes/baseRouter.js, routes/snippetRouter.js, views/layout.pug
Fixes #256, as described in https://github.com/janoside/btc-rpc-explorer/issues/256#issuecomment-739534905.
=> Switch markdown library and verify expected format

.env-sample, README.md, app.js, app/sso.js
This implements ThunderHub-like SSO. When activated, a token needs to be
passed in query on the first access, then a fresh cookie is used to
authenticate. The token is updated with each authenticated user to avoid
vulnerability stemming from leaking the token in browser history.
Closes #259
=> Implemented SSO

app.js
=> Add convenience redirection to the base URL

app.js
=> Add http:// in one more place

app/sso.js
This explains in details all relevant lines of code in hope to warn
the contributors of potential dangers around modifying it.
=> Detailed documentation of SSO code

README.md
Hey Dan, 
I  created a [AUR](https://aur.archlinux.org/packages/btc-rpc-explorer/) package for btc-rpc-explorer.
Thanks for your hard work. 
- Doug
=> Adding AUR arch linux install instructions

app/coins/btcFun.js
Another bitcoin history event.
=> Added multiple OP_CHECKSIG tx

Dockerfile
=> Dockerfile: update node to v16

app/coins/btc.js
0xB10C/known-mining-pools redirects to bitcoin-data/mining-pools
=> Update the 0xB10C pool URL

app/utils.js
=> Don't strip trailing zeros from values

routes/baseRouter.js, views/extended-public-key.pug, views/fun.pug
- global balance in header
- balance and transaction count in each address
- possibility to use extended public keys in btcFun.js
=> Improved xyzpub screen with some address details

pnpm-lock.yaml, routes/baseRouter.js
Closes #499 :3
Seems like the callback doesnt finish in time, switching to the promise overload of `qrcode.toDataURL` keeps it in line
=> Fix QR code not loading on address page

app/coins/btcHolidays.js
Hungarian name (without accents) is Laszlo, see
https://en.wikipedia.org/wiki/L%C3%A1szl%C3%B3
=> btcHolidays: fix the name
